const trackDir = "";
const bpm = 122.60;

const parts = [
    { file: "1.wav", length: 4,  loop: 1 },
    { file: "2.wav", length: 4,  loop: 1 },
    { file: "3.wav", length: 4,  loop: 1 },
    { file: "4.wav", length: 4,  loop: 1 },
    { file: "5.wav", length: 4,  loop: 1 },
    { file: "6.wav", length: 4,  loop: 1 },
    { file: "7.wav", length: 4,  loop: 1 },
    { file: "8.wav", length: 4,  loop: 1 },
    { file: "9.wav", length: 4,  loop: 1 },
    { file: "10.wav", length: 4,  loop: 1 },
    { file: "11.wav", length: 4,  loop: 1 },
    { file: "12.wav", length: 4,  loop: 1 },
    { file: "13.wav", length: 4,  loop: 1 },
    { file: "14.wav", length: 4,  loop: 1 },
    { file: "15.wav", length: 4,  loop: 1 },
    { file: "16.wav", length: 4,  loop: 1 },
    { file: "17.wav", length: 4,  loop: 1 },
    { file: "18.wav", length: 4,  loop: 1 },
    { file: "19.wav", length: 4,  loop: 1 },
    { file: "20.wav", length: 4,  loop: 1 },
    { file: "21.wav", length: 4,  loop: 1 },
    { file: "22.wav", length: 4,  loop: 1 },
    { file: "23.wav", length: 4,  loop: 1 },
    { file: "24.wav", length: 4,  loop: 1 },
    { file: "25.wav", length: 4,  loop: 1 },
    { file: "26.wav", length: 4,  loop: 1 },
    { file: "27.wav", length: 4,  loop: 1 },
    { file: "28.wav", length: 4,  loop: 1 },
    { file: "29.wav", length: 4,  loop: 1 },
    { file: "30.wav", length: 4,  loop: 1 },
    { file: "31.wav", length: 4,  loop: 1 },
    { file: "32.wav", length: 4,  loop: 1 },
    { file: "33.wav", length: 4,  loop: 1 },
    { file: "34.wav", length: 4,  loop: 1 },
    { file: "35.wav", length: 4,  loop: 1 },
    { file: "36.wav", length: 4,  loop: 1 },
    { file: "37.wav", length: 4,  loop: 1 },
    { file: "38.wav", length: 4,  loop: 1 },
    { file: "39.wav", length: 4,  loop: 1 },
    { file: "40.wav", length: 4,  loop: 1 },
    { file: "41.wav", length: 4,  loop: 1 },
    { file: "42.wav", length: 4,  loop: 1 },
    { file: "43.wav", length: 4,  loop: 1 },
    { file: "44.wav", length: 4,  loop: 1 },
    { file: "45.wav", length: 4,  loop: 1 },
    { file: "46.wav", length: 4,  loop: 1 },
    { file: "47.wav", length: 4,  loop: 1 },
    { file: "48.wav", length: 4,  loop: 1 },
    { file: "49.wav", length: 4,  loop: 1 },
    { file: "50.wav", length: 4,  loop: 1 },
    { file: "51.wav", length: 4,  loop: 1 },
    { file: "52.wav", length: 4,  loop: 1 },
    { file: "53.wav", length: 4,  loop: 1 },
    { file: "54.wav", length: 4,  loop: 1 },
    { file: "55.wav", length: 4,  loop: 1 },
    { file: "56.wav", length: 4,  loop: 1 },
    { file: "57.wav", length: 4,  loop: 1 },
    { file: "58.wav", length: 4,  loop: 1 },
    { file: "59.wav", length: 4,  loop: 1 },
    { file: "60.wav", length: 4,  loop: 1 },
    { file: "61.wav", length: 4,  loop: 1 },
    { file: "62.wav", length: 4,  loop: 1 },
    { file: "63.wav", length: 4,  loop: 1 },
    { file: "64.wav", length: 4,  loop: 1 },
    { file: "65.wav", length: 4,  loop: 1 },
    { file: "66.wav", length: 4,  loop: 1 },
    { file: "67.wav", length: 4,  loop: 1 },
];

const presets = [];
presets.push([ 

    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1

]);
presets.push([    
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
]);
presets.push([ 
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
]);
presets.push([ 
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
]);

const svgElement2 = document.getElementById('statusScriptIcon');
const newSvgContent2 = `
<circle cx="20" cy="20" r="18" stroke="#CEC6B3" stroke-width="4" fill="#576B68" />
<path d="M13 20 l5 5 l10 -10" stroke="#CEC6B3" stroke-width="4" fill="none" />`;

document.getElementById("statusScript").innerHTML = "Visual Assets Loaded";
document.getElementById('statusScript').style.color = '#90A423';
svgElement2.innerHTML = newSvgContent2;

const downloadName = "Audio_Soul_Project_(Deliver_Me_DUB)_EDIT.wav"
const boxHeight = 60; //min height == 40 -> otherwise clickable buttons are to small
const reverseScrolling = false;
